 insert into user values(1, sysdate(), 'AB')
 insert into user values(2, sysdate(), 'Jack')
 insert into user values(3, sysdate(), 'Jill')
 insert into post values(11001, 'My First Post' , 1)
 insert into post values(11002, 'My Second Post' , 2)
